apiVersion: v1
kind: ConfigMap
metadata:
  name: domtok-etcd-config
data:
  # 3.1 配置文件：config.yaml
  config.yaml: |
    server:
      private-key: | # PKCS#8
        -----BEGIN PRIVATE KEY-----
        MC4CAQAwBQYDK2VwBCIEIJi1JE7fq4xFZTXiOWvK9PDEDVIOgsF0dMF46BMgT9jY
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MCowBQYDK2VwAyEAe8QtuyTwO7YgDmZegsPpPPGuMZkjg6209OoArIOVOz0=
        -----END PUBLIC KEY-----
      version: "1.0"
      name: "DomTok"
      log-level: "INFO"
      intranet-url: "http://localhost:20001"

    administrator:
      secret: "$2a$14$6sUXbvlFBBdkm75aeQXXae0k8yKhSFVVQzqRZJU.qDH4r1/LzB8v."

    defaultUser:
      account: ""
      password: ""

    snowflake:
      datacenter-id: 0

    mysql:
      addr: 127.0.0.1:3306
      database: DomTok
      username: DomTok
      password: DomTok
      charset: utf8mb4

    oss:
      endpoint: ""
      accessKey-id: ""
      accessKey-secret: ""
      bucketname: ""
      main-directory: DomTok

    elasticsearch:
      addr: 127.0.0.1:9200
      host: 127.0.0.1

    redis:
      addr: 127.0.0.1:6379
      password: DomTok

    jaeger:
      addr: 127.0.0.1:6831

    kafka:
      address: 127.0.0.1:9092
      network: tcp
      user: domtok
      password: domtok-password

    upyun:
      bucket: "w2-domtok"
      operator: "penqee"
      password: "FuppKlbz13ukWRxQfKo3YlcplmiWUGyp"
      token-secret: ""
      token-timeout: 60
      uss-domain: "http://v0.api.upyun.com/w2-domtok"
      download-domain: "http://w2-domtok.test.upcdn.net"
      path: ""

    rocketmq:
      brokerAddr: 127.0.0.1:10911
      nameSrvAddr: 127.0.0.1:9876
      accessKey: DomTok
      secretKey: DomTok

    otel:
      collector-addr: 127.0.0.1:4317

    volcengine:
      api-key: "5fe08756-1e25-402f-8f8f-6c32d1035ed9"
      base-url: "https://ark.cn-beijing.volces.com/api/v3"
      region: "cn-beijing"
      model: "ep-20250211231153-286zf"

    services:
      template:
        name: template
        load-balance: false
        addr:
          - 127.0.0.1:10001

      gateway:
        name: gateway
        load-balance: false
        addr:
          - 0.0.0.0:20001

      user:
        name: user
        load-balance: false
        addr:
          - 0.0.0.0:20002

      order:
        name: order
        load-balance: false
        addr:
          - 0.0.0.0:20003

      commodity:
        name: commodity
        load-balance: false
        addr:
          - 0.0.0.0:20004

      payment:
        name: payment
        load-balance: false
        addr:
          - 0.0.0.0:20005

      cart:
        name: cart
        load-balance: false
        addr:
          - 0.0.0.0:20006

      assistant:
        name: assistant
        load-balance: false
        addr:
          - 0.0.0.0:20007

    # 3.2 脚本：etcd-monitor.sh
  etcd-monitor.sh: |
    #!/bin/bash
    # This script is used to monitor local files.
    # If there are any changes in the local files, they will be synchronized and updated to etcd.
    # Then etcd will update the configuration on other servers.

    # wait etcd complete
    while true; do
      if etcdctl endpoint health; then
        echo "etcd is ready."
        break
      fi
      echo "waiting for etcd to start..."
      sleep 1
    done

    # upload config
    etcdctl put /config -- < /config/config.yaml

    # create backup
    cp /config/config.yaml /config/config.yaml.bak

    # continuous listen
    previous_hash=$(sha256sum /config/config.yaml | awk '{print $1}')

    while true; do
      current_hash=$(sha256sum /config/config.yaml | awk '{print $1}')

      if [ "$current_hash" != "$previous_hash" ]; then
        etcdctl put /config -- < /config/config.yaml
        echo "spot update, config updated in etcd. $(date +'%Y-%m-%d %H:%M:%S')"
        # diff
        echo "Detected changes in configuration:"
        diff /config/config.yaml.bak /config/config.yaml
        cp /config/config.yaml /config/config.yaml.bak
        previous_hash="$current_hash"
      fi

      sleep 60
    done
