# Service (对外提供访问)
apiVersion: v1
kind: Service
metadata:
  name: domtok-mysql
spec:
  # 通过这个标签选择要绑定的 Pod（StatefulSet 会给 Pod 打上 app=domtok-mysql）
  selector:
    app: domtok-mysql
  # 若只需在集群内访问，可改成 ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort

---
# StatefulSet 部署 MySQL
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: domtok-mysql
spec:
  # 与 Service 同名，用于构建有状态 Pod 的 DNS
  serviceName: "domtok-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: domtok-mysql
  template:
    metadata:
      labels:
        app: domtok-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "domtok"
            - name: MYSQL_USER
              value: "domtok"
            - name: MYSQL_PASSWORD
              value: "domtok"
            - name: LANG
              value: "C.UTF-8"
            - name: TZ
              value: "Asia/Shanghai"

          # 数据卷和初始化脚本的挂载
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql

      # 引用创建的 PVC 和 ConfigMap
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-sql
          configMap:
            name: mysql-init-sql
